/**
 * Skills Section Island Entry Point
 *
 * Mounts SkillsSection component as a Preact island.
 *
 * Copilot: This island must be mounted in index.html at #skills-section-root.
 * Never duplicate or remove this mount point. The component fetches from
 * /skills.json which is generated by `pnpm skills:gen`.
 */

import { render } from 'preact';
import { SkillsSection } from './components/SkillsSection';

const root = document.getElementById('skills-section-root');
if (root) {
  render(<SkillsSection />, root);
  console.log('✅ SkillsSection mounted');
} else {
  console.warn('⚠️ SkillsSection: mount point #skills-section-root not found');
}
