overview:
  description: >
    Generate and maintain a high-level JSON overview of this repository.
    Follow the format shown in overview.json. Include:
      - metadata (name, description, languages, context)
      - structure (frontend, backend, tests, config)
      - core_components
      - infrastructure (docker, ci_cd, cloud)
      - dependencies
      - tests & docs
      - skills (technical skills demonstrated by the repo, useful for recruiters)
    Always reflect the *current state of the repo* without hallucination.
  format: json
  output: overview.json
