version: "3.9"

services:
  web-test:
    image: nginx:1.27-alpine
    container_name: web-test
    ports:
      - "5178:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.test.conf:/etc/nginx/conf.d/default.conf:ro
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/healthz" ]
      interval: 3s
      timeout: 2s
      retries: 20
      start_period: 5s
