version: "3.9"

# Optional tunnel sidecar. Launch with:
#   export CLOUDFLARE_TUNNEL_TOKEN=$(cat secrets/cloudflared_token)
#   docker compose -f deploy/docker-compose.prod.yml -f deploy/docker-compose.tunnel.override.yml up -d cloudflared
# Or via Makefile target (see tunnel-up).
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
    environment:
      - TUNNEL_TRANSPORT_PROTOCOL=auto
    depends_on:
      - backend
    # By default Cloudflare will route to the hostname configured for this token.
    # Configure ingress rules in Cloudflare dashboard if you need to expose nginx instead of backend.
