version: "3.9"
services:
  ollama:
    image: ollama/ollama:latest
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    volumes:
      - ollama:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ../assistant_api
    env_file:
      - ../assistant_api/.env.prod
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OPENAI_BASE_URL=http://ollama:11434/v1
      - OPENAI_MODEL=gpt-oss:20b
      # Secret files (optional): set either *_API_KEY or *_API_KEY_FILE to use mounted secrets
      - FALLBACK_API_KEY_FILE=/run/secrets/openai_api_key
      - OPENAI_API_KEY_FILE=/run/secrets/openai_api_key
    volumes:
      - ../data:/app/data
    depends_on:
      - ollama
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ready"]
      interval: 30s
      timeout: 5s
      retries: 3
    secrets:
      - openai_api_key

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped

volumes:
  ollama:

secrets:
  openai_api_key:
    file: ../secrets/openai_api_key
