version: "3.9"
services:
  ollama:
    image: nginx:alpine
    container_name: mock-ollama
    volumes:
      - ./mock-ollama.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "127.0.0.1:11435:11434"  # host port changed from 11434 to avoid local conflict
    healthcheck:
      test: ["CMD-SHELL", "pidof nginx || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 5s

  backend:
    build:
      context: ..
      dockerfile: assistant_api/Dockerfile.ci
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - ENV=ci
      - ALLOW_DEV_ROUTES=1
      - ALLOW_TEST_ROUTES=1
      - SEO_LLM_ENABLED=0
      - SEO_SITEMAP_CACHE=1
      - DATABASE_URL=sqlite:///./ci.sqlite3
      - PUBLIC_API_ORIGIN=http://127.0.0.1:8001
      - ALLOWED_ORIGINS=http://127.0.0.1:8001
      - DISABLE_AUTH=1
      - OLLAMA_HOST=ollama
      - OPENAI_BASE_URL=http://ollama:11434/v1
      - OPENAI_MODEL=gpt-oss:20b
      - PRIMARY_MODEL=${PRIMARY_MODEL:-gpt-oss:20b}
      - DISABLE_PRIMARY=0
    ports:
      - "8001:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/ready"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s
