version: "3.9"

# Local-only override: bind-mount the nginx server config so changes to deploy/nginx.conf
# are reflected immediately without rebuilding the image. Use together with the dist bind
# override for rapid iteration on both config and frontend assets.
#
# Usage (from repo root):
#   pnpm build:prod
#   docker compose \
#     -f deploy/docker-compose.prod.yml \
#     -f deploy/docker-compose.prod.bind.override.yml \
#     -f deploy/docker-compose.prod.conf.override.yml \
#     up -d --build
#
# Then verify with: docker compose -f deploy/docker-compose.prod.yml -f deploy/docker-compose.prod.bind.override.yml -f deploy/docker-compose.prod.conf.override.yml exec nginx nginx -T | grep X-Config
#
services:
  nginx:
    volumes:
      - type: bind
        source: ./nginx.conf   # path is relative to deploy/ directory
        target: /etc/nginx/conf.d/default.conf
        read_only: true
