# Portfolio Docker Compose Deployment
# This file can be deployed directly to your server running docker-compose
# Includes Watchtower for automatic updates when new images are pushed

services:
  portfolio-ui:
    image: ghcr.io/leok974/leo-portfolio/portfolio:latest
    container_name: portfolio-ui
    restart: unless-stopped
    networks:
      infra_net:
        aliases:
          - portfolio-ui
    ports:
      - "80:80"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 5s

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks: [infra_net]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: >
      --label-enable
      --cleanup
      --interval 60
      portfolio-ui

networks:
  infra_net:
    external: true
