"""Agent Act - Autonomous PR Generator

Endpoint for creating GitHub PRs from artifacts in /agent/artifacts/**.
Protected by SITEAGENT_ENABLE_WRITE=1 environment variable.
"""
from __future__ import annotations
import os
import json
import subprocess
from pathlib import Path
from typing import Optional
from fastapi import APIRouter, Body, Depends, HTTPException
from pydantic import BaseModel

router = APIRouter(prefix="/agent", tags=["agent"])

ARTIFACTS_DIR = Path("agent/artifacts")


# ============ Models ============

class PRCreateInput(BaseModel):
    """Input for PR creation."""
    branch: Optional[str] = None
    title: Optional[str] = None
    body: Optional[str] = None
    labels: list[str] = ["auto", "siteagent"]
    base: str = "main"
    commit_message: Optional[str] = None
    dry_run: bool = False
    use_llm: bool = False  # Enable LLM-generated title/body


class PRCreateResponse(BaseModel):
    """Response from PR creation."""
    status: str
    branch: Optional[str] = None
    pr: Optional[str] = None
    labels: Optional[list[str]] = None
    diff: Optional[str] = None
    message: Optional[str] = None


# ============ Guards ============

def _dev_guard():
    """Verify SITEAGENT_ENABLE_WRITE=1 is set."""
    if os.getenv("SITEAGENT_ENABLE_WRITE") != "1":
        raise HTTPException(
            status_code=403,
            detail="Write actions disabled. Set SITEAGENT_ENABLE_WRITE=1 to enable."
        )


# ============ Helpers ============

def _run(cmd: str, env: dict | None = None) -> str:
    """Run shell command and return stdout."""
    result = subprocess.run(
        cmd,
        shell=True,
        capture_output=True,
        text=True,
        env={**os.environ, **(env or {})}
    )
    if result.returncode != 0:
        raise Exception(
            f"Command failed: {cmd}\n"
            f"STDOUT: {result.stdout}\n"
            f"STDERR: {result.stderr}"
        )
    return result.stdout.strip()


def _ensure_gh():
    """Verify GitHub CLI is installed."""
    try:
        _run("gh --version")
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail="GitHub CLI (gh) not found. Install from https://cli.github.com/"
        ) from e


def _require_token() -> str:
    """Get GitHub token from environment."""
    tok = os.getenv("GITHUB_TOKEN") or os.getenv("GH_TOKEN")
    if not tok:
        raise HTTPException(
            status_code=500,
            detail="GITHUB_TOKEN or GH_TOKEN environment variable required"
        )
    return tok


def _repo_slug() -> str:
    """
    Get repository owner/name slug.
    Tries GITHUB_REPOSITORY env var first (set by Actions),
    then parses from git remote.
    """
    slug = os.getenv("GITHUB_REPOSITORY")
    if slug:
        return slug

    try:
        remote = _run("git config --get remote.origin.url")
        # Parse github.com:owner/repo.git or https://github.com/owner/repo.git
        if "github.com" in remote:
            parts = remote.replace(".git", "").split("github.com")[-1]
            return parts.strip("/:").strip()
    except Exception:
        pass

    raise HTTPException(
        status_code=500,
        detail="Could not determine repository slug. Set GITHUB_REPOSITORY env var."
    )


def _collect_artifacts(root: Path = ARTIFACTS_DIR) -> list[Path]:
    """Collect current artifact files; no caching, skip missing."""
    if not root.exists():
        return []
    files: list[Path] = []
    for p in root.rglob("*"):
        if p.is_file():
            files.append(p)
    return files


def _default_title_body(diff_summary: str) -> tuple[str, str]:
    """Generate default PR title and body from diff."""
    file_count = len([l for l in diff_summary.split("\n") if l.strip()])
    title = f"chore(siteagent): apply {file_count} artifact(s)"
    body = (
        "This PR was automatically generated by SiteAgent.\n\n"
        "## Changes\n\n"
        f"```\n{diff_summary}\n```\n"
    )
    return title, body


def _llm_title_body(diff_summary: str, insights: str = "") -> tuple[str, str]:
    """Generate PR title and body using LLM (with primary→fallback routing)."""
    try:
        from assistant_api.llm.router import chat_complete
    except ImportError:
        # Fall back to default if LLM router not available
        return _default_title_body(diff_summary)
    
    prompt = (
        "Create a concise PR title (<=72 chars) and a short PR body.\n"
        "Return format:\nTITLE: <one line>\nBODY:\n<short markdown body>\n\n"
        f"Diff summary:\n```\n{diff_summary}\n```\n\n"
        f"Latest analytics insight (optional):\n```\n{insights[:4000]}\n```"
    )
    
    try:
        model_used, text = chat_complete(
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
        )
        
        lines = [ln.strip() for ln in (text or "").splitlines() if ln.strip()]
        title_line = next(
            (ln[7:].strip() for ln in lines if ln.upper().startswith("TITLE:")),
            lines[0] if lines else "chore: update",
        )
        body_start = next(
            (i for i, ln in enumerate(lines) if ln.upper().startswith("BODY:")), None
        )
        body_lines = lines[body_start + 1 :] if body_start is not None else lines[1:]
        
        title = title_line[:72] or "chore: update"
        body = "\n".join(body_lines).strip() or "Auto-generated by SiteAgent."
        
        # Append which model was used
        body += f"\n\n<sub>LLM: {model_used}</sub>"
        
        return title, body
    except Exception as e:
        # Fall back to default on any LLM error
        print(f"[warn] LLM title/body generation failed: {e}")
        return _default_title_body(diff_summary)


# ============ Routes ============

@router.post("/act", dependencies=[Depends(_dev_guard)])
def agent_act(
    task: str,
    payload: PRCreateInput = Body(default=PRCreateInput())
):
    """
    Agent action dispatcher.

    Currently supports:
    - task=pr.create: Create GitHub PR from artifacts
    """
    if task == "pr.create":
        return create_pr(payload)

    raise HTTPException(
        status_code=400,
        detail=f"Unknown task: {task}"
    )


@router.post("/artifacts/pr", dependencies=[Depends(_dev_guard)])
def pr_alias(payload: PRCreateInput = Body(default=PRCreateInput())):
    """Alias for /agent/act?task=pr.create"""
    return create_pr(payload)


def create_pr(payload: PRCreateInput) -> dict:
    """
    Create a GitHub PR from artifacts in /agent/artifacts/**.

    Collects all files from /agent/artifacts/**, creates a new branch,
    commits the artifacts, pushes to GitHub, and opens a PR.

    Protected by SITEAGENT_ENABLE_WRITE=1 environment variable.

    Returns:
    - For dry_run=true: branch name and diff summary
    - For dry_run=false: PR URL, branch name, labels, and diff summary
    """
    # Verify gh CLI is installed
    _ensure_gh()

    # Only require token if not doing a dry-run
    tok = None
    repo = None
    if not payload.dry_run:
        tok = _require_token()
        repo = _repo_slug()

    # Collect artifacts (fresh on every call)
    files = _collect_artifacts()
    if not files:
        raise HTTPException(
            status_code=400,
            detail=f"No artifacts found in {ARTIFACTS_DIR}. Nothing to commit."
        )

    # Create working branch
    branch = payload.branch or f"siteagent/auto-{os.getpid()}"
    try:
        _run("git fetch origin")
        _run(f"git checkout -B {branch} origin/{payload.base}")
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to create branch {branch}: {str(e)}"
        ) from e

    # Copy artifacts into repo root with same relative paths
    repo_root = Path(".").resolve()
    for f in files:
        if not f.exists():  # skip anything that disappeared
            continue
        try:
            rel = f.relative_to(ARTIFACTS_DIR)
            out = repo_root / rel
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_bytes(f.read_bytes())
        except Exception as e:
            raise HTTPException(
                status_code=500,
                detail=f"Failed to copy artifact {f}: {str(e)}"
            ) from e

    # Stage changes and get diff summary
    try:
        _run("git add -A")
        diff_summary = _run("git status --porcelain")
    except Exception as e:
        diff_summary = f"(diff summary unavailable: {e})"

    if not diff_summary:
        return {
            "status": "noop",
            "message": "No changes to commit.",
            "branch": branch
        }

    # Commit changes
    commit_msg = payload.commit_message or "chore(siteagent): apply approved artifacts"
    try:
        # Escape quotes in commit message
        safe_msg = commit_msg.replace('"', '\\"')
        _run(f'git commit -m "{safe_msg}"')
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to commit changes: {str(e)}"
        ) from e

    # Dry run: return without pushing
    if payload.dry_run:
        return {
            "status": "dry-run",
            "branch": branch,
            "diff": diff_summary
        }

    # Push branch
    try:
        _run(f"git push -u origin {branch}")
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to push branch {branch}: {str(e)}"
        ) from e

    # Compose PR title and body
    title = payload.title
    body = payload.body
    if not title or not body:
        # Use LLM if requested and available, otherwise use default
        if payload.use_llm:
            # Try to load latest analytics insights for context
            insights = ""
            try:
                insight_file = Path("analytics/outputs/insight-summary.md")
                if insight_file.exists():
                    insights = insight_file.read_text(encoding="utf-8")
            except Exception:
                pass
            
            default_title, default_body = _llm_title_body(diff_summary, insights)
        else:
            default_title, default_body = _default_title_body(diff_summary)
        
        title = title or default_title
        body = body or default_body

    # Create PR with gh CLI
    env = {"GH_TOKEN": tok}
    try:
        # Escape quotes in title and body
        safe_title = title.replace('"', '\\"')
        safe_body = body.replace('"', '\\"')
        pr_url = _run(
            f'gh pr create --repo {repo} --base {payload.base} --head {branch} '
            f'--title "{safe_title}" --body "{safe_body}"',
            env=env
        )
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Failed to create PR: {str(e)}"
        ) from e

    # Apply labels
    labels = payload.labels or ["auto", "siteagent"]
    if labels:
        try:
            label_str = ",".join(labels)
            _run(f'gh pr edit {pr_url} --add-label "{label_str}"', env=env)
        except Exception as e:
            # Non-fatal: PR was created successfully
            print(f"[warn] Failed to apply labels: {e}")

    return {
        "status": "ok",
        "branch": branch,
        "pr": pr_url,
        "labels": labels,
        "diff": diff_summary
    }
