server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Nginx JSON logs (access logs)
  - job_name: nginx_json
    static_configs:
      - targets: [localhost]
        labels:
          job: nginx
          component: edge
          __path__: /var/log/nginx/access.json.log

    pipeline_stages:
      # Parse JSON log line
      - json:
          expressions:
            time: time
            remote_addr: remote_addr
            method: method
            uri: uri
            status: status
            body_bytes_sent: body_bytes_sent
            referrer: referrer
            agent: agent
            request_time: request_time
            upstream_response_time: upstream_response_time
            limit_req_status: limit_req_status

      # Extract labels for querying
      - labels:
          method:
          status:
          uri:
          limit_req_status:

      # Parse timestamp
      - timestamp:
          source: time
          format: RFC3339

      # Add derived metrics
      - metrics:
          request_duration_seconds:
            type: Histogram
            description: "Request duration in seconds"
            source: request_time
            config:
              buckets: [0.1, 0.5, 1.0, 2.0, 5.0]

  # Backend application logs (FastAPI uvicorn)
  - job_name: backend_logs
    static_configs:
      - targets: [localhost]
        labels:
          job: backend
          component: api
          __path__: /var/log/assistant_api/*.log

    pipeline_stages:
      # Try to parse as JSON (uvicorn --log-config can output JSON)
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
          source: message

      - labels:
          level:
          logger:

      - timestamp:
          source: timestamp
          format: RFC3339Nano

  # Metrics rotation logs (Python script output)
  - job_name: metrics_rotator
    static_configs:
      - targets: [localhost]
        labels:
          job: metrics_rotator
          component: maintenance
          __path__: /var/log/metrics_rotator/*.log

    pipeline_stages:
      # Simple regex for Python logging format
      - regex:
          expression: '(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}) - (?P<level>\w+) - (?P<message>.*)'

      - labels:
          level:

      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05"
