name: Agents Suite

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - "assistant_api/agents/**"
      - "assistant_api/routers/agents.py"
      - "src/components/Agents*"
      - "tests/api/test_agents*"
      - "tests/e2e/agents*"
      - "tests/e2e/helpers/**"
      - "playwright.config.ts"

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install backend deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip wheel
          pip install -r assistant_api/requirements.txt
      - name: API tests (agents)
        run: |
          source .venv/bin/activate
          pytest -q tests/api/test_agents*.py

  e2e:
    runs-on: ubuntu-latest
    needs: api
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install frontend deps
        run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Build frontend
        run: npm run build
      - name: Setup Python for backend
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install backend deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -U pip wheel
          pip install -r assistant_api/requirements.txt
      - name: Start backend
        run: |
          source .venv/bin/activate
          nohup python -m uvicorn assistant_api.main:app --host 127.0.0.1 --port 8001 >/dev/null 2>&1 &
          sleep 5
      - name: Verify backend health
        run: curl -f http://127.0.0.1:8001/ready || exit 1
      - name: Run E2E (agents)
        env:
          BASE_URL: http://localhost:5173
          CI: true
        run: npx playwright test "agents.*" --project=chromium --reporter=dot
      - name: Upload traces on fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 7
