name: Analytics Retention Weekly

on:
  schedule:
    - cron: "10 7 * * SUN"   # Sundays 03:10 ET (07:10 UTC)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  retention:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run retention
        env:
          ANALYTICS_RETENTION_DAYS: ${{ vars.ANALYTICS_RETENTION_DAYS || 90 }}
          ANALYTICS_GZIP_AFTER_DAYS: ${{ vars.ANALYTICS_GZIP_AFTER_DAYS || 7 }}
        run: |
          python scripts/analytics_retention.py

      - name: Commit changes if any
        run: |
          if git status --porcelain | grep -E "data/analytics/"; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A data/analytics
            git commit -m "chore(analytics): weekly retention (gzip/prune) [skip ci]" || echo "No commit"
            git push
          else
            echo "No analytics changes to commit."
          fi
