name: Behavior Learning Nightly

on:
  schedule:
    - cron: "30 6 * * *"  # 02:30 America/New_York (UTC-4) -> 06:30 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  learn-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run behavior analysis
        run: |
          python scripts/analyze_behavior.py

      - name: Commit weights if changed
        run: |
          if git diff --quiet -- data/analytics/weights.json; then
            echo "No change to weights.json"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/analytics/weights.json
          git commit -m "chore(analytics): nightly update weights.json [skip ci]"
          git push
