name: CI – Heavy (models)

on:
  schedule:
    - cron: "15 4 * * *"
  workflow_dispatch:

jobs:
  heavy-tests:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install heavy deps (CPU)
        run: |
          python -m pip install -U pip
          pip install --index-url https://download.pytorch.org/whl/cpu torch==2.4.0
          pip install -r assistant_api/requirements.txt

      - name: Run heavy tests
        run: pytest -m heavy -q
