name: CI

on:
  push:
    branches: [main, polish]
  pull_request:
    branches: [main, polish]

jobs:
  playwright-tests:
    name: Run E2E Tests (Playwright)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install chromium --with-deps

      - name: Build frontend
        run: npm run build:portfolio

      - name: Copy book.html to dist
        run: cp book.html dist-portfolio/book.html

      - name: Copy calendly.js to dist
        run: |
          mkdir -p dist-portfolio/assets/js
          cp public/assets/js/calendly.js dist-portfolio/assets/js/calendly.js

      - name: Copy dist-portfolio to dist for tests
        run: cp -r dist-portfolio dist

      - name: Run E2E Tests
        env:
          PW_APP: portfolio
          PW_BASE_URL: http://127.0.0.1:5174
          BACKEND_REQUIRED: "0"
        run: npx playwright test --reporter=html

      - name: Upload Playwright HTML report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Upload test traces
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
          retention-days: 7

  backend-tests:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r assistant_api/requirements.txt
          if [ -f assistant_api/requirements-dev.txt ]; then pip install -r assistant_api/requirements-dev.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Run pytest (fast-fail)
        env:
          APP_ENV: test
          RAG_DB_PATH: ":memory:"
          PRIMARY_MODEL: "qwen2.5:7b-instruct-q4_K_M"
          ENABLE_RAG: "false"
        run: pytest assistant_api/tests/ -q --tb=short --maxfail=5 --no-cov

      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          flags: backend
          name: backend-coverage

  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Node dependencies
        run: npm ci

      - name: Install Python dependencies
        run: |
          pip install ruff black mypy pip-audit
          pip install -r requirements-dev.txt

      - name: Run ESLint
        run: npm run lint

      - name: Run TypeScript check
        run: npx tsc --noEmit

      - name: Run Python linting (ruff)
        run: ruff check assistant_api/

      - name: Run Python formatting check (black)
        run: black --check assistant_api/

      - name: Run Python type check (mypy)
        run: mypy assistant_api/ --ignore-missing-imports

      - name: Run security audit (pip-audit)
        run: pip-audit -r requirements.txt

  smoke-tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r assistant_api/requirements.txt

      - name: Start backend service
        env:
          APP_ENV: test
          RAG_DB_PATH: ":memory:"
          PRIMARY_MODEL: "qwen2.5:7b-instruct-q4_K_M"
          DISABLE_PRIMARY: "1"
        run: |
          python -m uvicorn assistant_api.main:app --host 127.0.0.1 --port 8001 &
          echo $! > backend.pid
          sleep 5

      - name: Run smoke tests
        shell: pwsh
        run: pwsh -File scripts/smoke-ci.ps1 -BaseUrl "http://127.0.0.1:8001" -TimeoutSec 120

      - name: Dump backend logs on failure
        if: failure()
        run: |
          echo "::group::Backend Process Status"
          ps aux | grep uvicorn || true
          ps aux | grep python || true
          echo "::endgroup::"
          echo "::group::Backend PID"
          if [ -f backend.pid ]; then cat backend.pid; fi
          echo "::endgroup::"

      - name: Stop backend service
        if: always()
        run: |
          if [ -f backend.pid ]; then
            kill $(cat backend.pid) || true
          fi
          # Kill any remaining uvicorn processes
          pkill -f uvicorn || true

  build:
    name: Build & Verify
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build:portfolio

      - name: Verify build output
        run: |
          ls -lh dist-portfolio/
          test -f dist-portfolio/index.html

      # TODO: Re-enable when SRI manifest generation is implemented
      # - name: Check SRI manifest
      #   run: test -f dist-portfolio/sri-manifest.json

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-portfolio
          path: dist-portfolio/
          retention-days: 7
