name: deps-audit
on:
  push:
    paths: [ "assistant_api/requirements.txt", ".github/workflows/deps-audit.yml" ]
  pull_request:
    paths: [ "assistant_api/requirements.txt" ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('assistant_api/requirements.txt') }}
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r assistant_api/requirements.txt
      - name: pip-audit
        run: |
          python -m pip install pip-audit
          pip-audit --strict
