name: Docs & Workflows Audit
on:
  pull_request:
  push:
    branches: [ main ]

env:
  STRICT_AUDIT: ${{ (startsWith(github.ref, 'refs/heads/main') || startsWith(github.ref, 'refs/tags/')) && '1' || '0' }}
  KEEP_WORKFLOWS: "ci.yml,release.yml,docs-audit.yml,deploy.yml"
  DOCS_DELETE_GRACE_DAYS: "14"

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile || npm i

      - name: Docs audit (dry-run)
        run: pnpm run docs:audit

      - name: Workflows audit (dry-run)
        run: pnpm run wf:audit

      - name: Upload audit reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-workflows-audit
          path: |
            docs/consolidation-report*.json

      - name: Enforce (strict mode)
        if: env.STRICT_AUDIT == '1'
        run: |
          echo "🔒 Strict mode enabled on ${{ github.ref }}"
          node -e "const fs=require('fs');const f=fs.readdirSync('docs').find(x=>x.startsWith('consolidation-report'));const j=JSON.parse(fs.readFileSync('docs/'+f,'utf8')); if(!j) process.exit(1); if((j.flagged||[]).length>0){ console.error('Flagged docs remain'); process.exit(2);} "
          node -e "const fs=require('fs');const keep=(process.env.KEEP_WORKFLOWS||'ci.yml,release.yml,deploy.yml').split(','); const found=fs.readdirSync('.github/workflows').filter(f=>/\.(yml|yaml)$/.test(f)); const extras=found.filter(f=>!keep.includes(f)); if(extras.length){ console.error('Extra workflows:', extras.join(', ')); process.exit(3);} "
          echo "✅ All strict mode checks passed"
