name: e2e-ui-polish

on:
  pull_request:
    paths:
      - "tests/e2e/**"
      - "src/styles/**"
      - "tailwind.config.*"
      - "package.json"
      - ".github/workflows/e2e-ui-polish.yml"
  schedule:
    - cron: "0 9 * * 1" # Mondays 09:00 UTC (drift check)

concurrency:
  group: e2e-ui-polish-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ui-polish:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PLAYWRIGHT_GLOBAL_SETUP_SKIP: "1"
      BASE_URL: "http://127.0.0.1:5173"

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build site
        run: pnpm run build --if-present || true

      - name: Install Playwright (cached)
        uses: microsoft/playwright-github-action@v1
        with:
          version: 1.x
          browsers: chromium

      - name: Verify tw-animate-css import present
        run: grep -R "tw-animate-css" -n src/styles || (echo "Missing tw-animate-css import" && exit 1)

      # --- UI polish suite ---
      - name: Run UI polish tests (fail fast)
        run: npx playwright test -g "@ui-polish" --project=chromium --max-failures=1 --reporter=line,junit

      - name: Rename JUnit (ui-polish)
        run: if [ -f junit.xml ]; then mv junit.xml junit-ui-polish.xml; fi

      # --- Analytics beacons suite ---
      - name: Run analytics beacons suite (fail fast)
        run: npx playwright test -g "@analytics-beacons" --project=chromium --max-failures=1 --reporter=line,junit

      - name: Rename JUnit (analytics)
        run: if [ -f junit.xml ]; then mv junit.xml junit-analytics-beacons.xml; fi

      # Upload HTML report for quick triage
      - name: Generate HTML report (on failure)
        if: failure()
        run: npx playwright show-report --output=playwright-report || true

      # Artifacts on failure for fast repro
      - name: Collect diagnostics (on failure)
        if: failure()
        shell: pwsh
        run: pwsh ./scripts/collect-diag.ps1

      - name: Upload diagnostics
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diag-bundle
          path: artifacts/**
          retention-days: 7

      - name: Upload HTML report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/**
          retention-days: 7

      - name: Upload Playwright results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-results
          path: |
            test-results/**
            junit*.xml
          retention-days: 7

      - name: Annotate PR with test results
        if: failure()
        uses: mikepenz/action-junit-report@v4
        with:
          report_paths: "junit*.xml"
          check_name: "Playwright Tests (UI Polish)"
          include_passed: false
          annotate_only: true
