name: Link Check
on:
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  linkinator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g linkinator
      - run: linkinator https://leok974.github.io/leo-portfolio/ --recurse --timeout 30000
