name: Lint Deploy Docs

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint deploy/doc sync
        shell: pwsh
        run: pwsh ./scripts/lint-deploy.ps1
      - name: Lint env template
        shell: pwsh
        run: pwsh ./scripts/lint-env-template.ps1
