name: Publish Backend (GHCR)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/backend

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      PYTHONPATH: ${{ github.workspace }}
      DEV_HMAC_KEY: test-dev-key-123
      CF_ACCESS_AUD: test-aud
      CF_ACCESS_TEAM_DOMAIN: test-team.cloudflareaccess.com
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('assistant_api/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-
      - name: Install deps (backend)
        working-directory: assistant_api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          python -m pytest -q tests/test_status_rag.py || python -m pytest -q

  build-and-push:
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      
      - uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Free disk space
        run: |
          echo "=== Disk space before cleanup ==="
          df -h
          sudo docker system prune -af --volumes || true
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc || true
          echo "=== Disk space after cleanup ==="
          df -h

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Short SHA
        id: meta
        run: echo "short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build & Push (amd64 only - temporary)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/Dockerfile.backend
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:main
            ${{ env.IMAGE_NAME }}:sha-${{ steps.meta.outputs.short }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Prune buildx cache
        if: always()
        run: |
          docker buildx prune -af || true
          df -h
